### ISSUE TITLE
Conditions: verificationStatus constraints 

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#11]
On 5/10 we agreed to constrain verificationStatus for Conditions to only allow: unconfirmed, provisional, differential, and confirmed.

Said another way, do not allow: refuted, and entered in error

**Comment by mickohanlon23** [comment]
[verificationStatus](http://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-condition-problems-health-concerns-definitions.html#Condition.verificationStatus) is not a required element according to U.S. Core, so I think there could be slight differences in the two ways you explained how we want to constrain it, depending on how you interpret "constrain".

To clarify, we are not requiring a condition to have a `verificationStatus`, but if it does exist, the Condition will only display on the Dashboard and be used in the CDS if the code is not `refuted` or `entered-in-error`, right?

**Comment by ssebast2** [comment]
Correct!

**Comment by mickohanlon23** [comment]
This is addressed in commit https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/commit/d83034ca996cf2d04c9c8bd4836a505891a726f1, which adds a helper function to our CDS that filters all Condition queries to only include a Condition in the Dashboard and in the CDS logic if it doesn't have a verificationStatus of `refuted` or `entered-in-error`. I added 2 tests to verify this functionality.
