### ISSUE TITLE
Conditions: clinicalStatus constraints

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#12]
On 5/10, we agreed to the following:

Constrain Premenopausal (i.e., dx of premenopausal) to: active, recurrence, relapse
Constrain Dx of Pregnancy to: active

All other diagnosis' will not be constrained

(Of note, although it would be appropriate to constrain Dx of abnormal uterine/vaginal bleeding and Dx of cervical/vaginal lesion to only active, recurrence, and relapse, we opted not to since the tight lookback period of 24 hours lessens the need for this constraint.)

**Comment by mickohanlon23** [comment]
In commit https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/commit/dfafabcc4891107f5927775e55b804a825d5f710,  I:
1) Restricted Premenopausal Condition to have a clinical status of `active`, `recurrence`, or `relapse`.
2)  Tightened the constraints of Pregnancy to require a clinical status of `active`.

Note: Pregnancy currently _requires_ a `verificationStatus` of `confirmed`, which is tighter than the constraint on the verificationStatuses of the rest of the Conditions. Is this still accurate @ssebast2?

**Comment by ssebast2** [comment]
@mickohanlon23  - what you stated above is correct.

**Comment by mickohanlon23** [comment]
@ssebast2 Great, all changes here have been updated in the L3. I'll close out this issue.
