### ISSUE TITLE
Observations: Attributes for Labs

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#13]
Mick mentioned that the L3 includes the following attributes and constraints:
- code
- status = final, corrected, or amended
- valueCodeableConcept
- effective[x]
- issued

The clinicians do not understand why 'issued' has been included in the L3 code. We need to know when the specimen was collected (i.e., the effective date). If you feel that issued is relevant, please share the rationale.

**Comment by mickohanlon23** [comment]
`Observation.effective[x]` is not _technically_ a required element by U.S. Core. It has `0..1` cardinality, even though the comments in the Structure Definition say: "At least a date should be present unless this observation is a historical report" (see http://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-observation-lab-definitions.html#Observation.effective[x]).

When looking for the date, `Observation.issued` is only queried if the `effective[x]` date is not present. So it is more of a fallback than a data requirement.

I figure it's better to have the issued date than no date at all in the circumstance I mentioned above, but let me know if you foresee any issues with this. Feel free to remove this from the data requirements sheet if you think it is confusing.

**Comment by ssebast2** [comment]
Understanding the prioritization of the two data elements is very helpful. It makes sense and is reasonable to only use .issued if .effective[x] is not available. Thanks!
