### ISSUE TITLE
Condition: Adding dateTimes to Premenopausal and Postmenopausal

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#20]
Mick entered a comment in the DER that only .code and .clincialStatus are specified in the L3 b/c the date is not required by the CDS. However, the date is relevant to display on the dashboard. Every entry in the dashboard should have an associated date. Especially these diagnoses since women transition to/through them.

**Comment by mickohanlon23** [comment]
Hi Sharon, a few things here:

1) Premenopausal and Postmenopausal are not currently displayed in the Dashboard. I believe this is because they were not added to the "DISPLAY data elements used in the Cervical Cancer Screening and Management (CCSM) Dashboard" section within the CDS Actions of Logic Path 1 in the L2 (page 15). They only come up in their respective sections in Rare Abnormalities Management. Would you like us to add them?

2) Premenopausal and Postmenopausal are currently queried as Observations, not Conditions. I can't remember exactly why this was, but I believe it may be be because some of the codes descend from the "Clinical Finding" SNOMED concept. Should these both be changed to Conditions? If so, should we include any constraints on the elements of the Conditions?

3) I definitely agree that we want all Dashboard elements to include a date. The reason `date` wasn't specified was because these two concepts are not currently displayed in the Dashboard, but if the answer to question 1 is yes, then a date will be added.

**Comment by ssebast2** [comment]
I'll talk to Rose about this. I can see it being recorded as an Observation or a Diagnosis - especially postmenpausal.

**Comment by ssebast2** [comment]
@mickohanlon23 - Rose and I spoke and agreed that it would be most beneficial to cast a larger net when looking for evidence of  premenopausal or postmenopausal. When we originally wrote the logic and defined the VSs, we did it in the context of both being diagnoses, so there is a disconnect between the L2 and L3. In addition, some of the L3 code will have to be corrected r/t these menopausal concepts when recorded as an observation b/c we cannot use ICD9 and ICD10 codes to represent an Observation.

I have:

-  updated the logic in LP5 section G.4 in the L2 to look for pre and post menopause as a condition and observation
- updated the logic in the dashboard section of the L2 to include menopausal concepts as a condition and observation
- updated the VS spreadsheet to include observations and conditions - Note: the coded definitions as different. The L3 code will need to be changed when using an observation resource. 
- Rose and I also plan to update the Pilot data element requirement (DER) spreadsheet and the appendix in the IG r/t data requirements.

**Comment by mickohanlon23** [comment]
Thanks @ssebast2. Makes sense to cast a wide net. In commit https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/commit/630ae13602b401b1dfee1b0334385856672bcb83, I:
- Added Premenopausal and Postmenopausal to the dashboard, both:
   1. As a Condition
       - Premenopausal and Postmenopausal look for all of the Condition codes that were already included in the ValueSet spreadsheet (2 ICD codes and a SNOMED VS for premenopausal, 1 SNOMED code for postmenopausal)
       - Conditions are constrained just by verification status, as was resolved in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/issues/11
   2. As an Observation
       - Premenopausal and Postmenopausal look for Observations with a `code` element from the same codes as above, but not including the ICD codes (Just the SNOMED VS for premenopausal and the same SNOMED code for postmenopausal). 
       - Observations are constrained to have a status of `final`, `corrected`, or `amended`, as is true for the rest of the dashboard Observations and is explained by the dashboard section of the L2.
 - Modified LP5 section G.4 to look for premenopausal and postmenopausal as both a Condition and an Observation (constrained by the same Dashboard logic described above).

Does this update align with the conversations you and Rose had?

**Comment by ssebast2** [comment]
@mickohanlon23  - what you outlined above is correct.  We need to display premenopausal and postmenopausal in the dashboard since we will be providing a care recommendation based on evidence of these things in the patient record. Any time we post something on the dashboard, a date should also be included. 

I have included 'onsetDateTime' and 'recordedDate' for diagnoses in the data element requirement sheet. Please let me know if you have a concern with this.

**Comment by mickohanlon23** [comment]
Great, the dates for premenopausal and postmenopausal are included in the dashboard display, as is the case for the rest of the dashboard resources.

No issue with the addition of both date elements to the data element sheet. Both elements come up in the L3 code when displaying the date to the Dashboard.

**Comment by mickohanlon23** [comment]
I stated the following above:

> Conditions are constrained just by verification status, as was resolved in #11


There is now one correction to this, and that is that Premenopausal Conditions are also constrained to have a `clinicalStatus` of active, recurrence or relapse, as was decided in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/issues/12 (and now updated in the L3 code). I'm going to close this issue our as it was pretty clear from our discussion in the other issue that this is the correct way to go, but feel free to re-open if you see any problems with this.
