### ISSUE TITLE
Attributes for Encounter

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#22]
@mickohanlon23  - We added "encounter" as a data element on the DER for eCQMs and CDS Evaluation Metrics.  Would you mind taking a look at the FHIR attributes I listed to see if they make sense to you. Is there anything else I should add? (I realize that 'encounter' is not used in the CDS, so this is outside the immediate context of our CDS).

**Comment by mickohanlon23** [comment]
@ssebast2  Are you referring to the last two rows within [CCSM Data Element Requirements 6.21.22](https://mitre.sharepoint.com/:x:/r/sites/CervicalCancerCDS/_layouts/15/Doc.aspx?sourcedoc=%7B509ACCF0-E202-424A-997E-1FA2125C3D32%7D&file=CCSM%20Data%20Element%20Requirements_updated_6.21.22.xlsx&nav=MTBfezVBMkRFNkQ0LUU2MDMtNEFFNS1CMkVBLUQ5NTY3ODRDRUZGNX1fezE0OTE1OUJDLUE5QUUtNDBFNi1CQTlELThGMkNBNkY1MEE1MH0&action=default&mobileredirect=true)?

The CDS looks for Encounters in one place - to check for an Encounter that had a `reasonCode` of an abnormal bleeding code. These Encounters are used as inclusion criteria for LP1 and are also displayed in the Dashboard. The following `Encounter` elements are used:
- reasonCode (must be in "Abnormal Uterine or Vaginal Bleeding Disorders" or "Abnormal Uterine or Vaginal Bleeding Findings" value set)
- status (triaged, in-progress, or finished)
- period (to get the start and end time)

As for the use of Encounters within the eCQMs I would defer to @matthewtiller.

**Comment by mickohanlon23** [comment]
@ssebast2
1. Added row to the DER looks good!
2. We don't restrict these encounters to any value set. What element are you talking about restricting specifically? Does this matter? Shouldn't any encounter with a reasonCode referring to abnormal uterine or vaginal bleeding be considered relevant?
3. We currently restrict the status of these encounters to triaged, in-progress, or finished).

**Comment by ssebast2** [comment]
I asked about the value set constraint from an eCQM and pilot evaluation perspective. It makes sense for you not to restrict it from a CDS/L3 perspective - if a clinician is in the midst of an encounter and they record info about abnormal bleeding, that should 'count'. 

From an eCQM and pilot eval perspective - we would only 'ding' a clinician if they didn't perform evidence-based care during specific types of encounters (i.e., the types defined in our value sets). 

I think it will be clearest to create a 3rd row for encounters in the VS and DER spreadsheets. The CDS row will not constrain the type of encounter, whereas eCQMs and pilot metrics will.

**Comment by mickohanlon23** [comment]
That makes sense to me! I'll close out this issue here, since it requires no further updates to the L3 CDS.
