### ISSUE TITLE
npm script for packager.js

### ISSUE THREAD

**Issue by dwwinters** [ccsm-cds-tools/ccsm-cds-with-tests#30]
@dwwinters It would be nice to have an npm script that could run this, as well as a mention of this functionality in the README.

_Originally posted by @mickohanlon23 in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/23#discussion_r918196113_

**Comment by mickohanlon23** [comment]
Started in `add-packager-script` branch: https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/tree/add-packager-script
