### ISSUE TITLE
user-friendly way to handle the date text if only a start time exists

### ISSUE THREAD

**Issue by dwwinters** [ccsm-cds-tools/ccsm-cds-with-tests#31]
@dwwinters Should we include a user-friendly way to handle the date text if only a start time exists (ex. for an active medication). What about for a date represented as a DateTime versus as a Period?

(NOTE: This applies to MedicationAdministration as well.)

_Originally posted by @mickohanlon23 in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/23#discussion_r918223864_

**Comment by mickohanlon23** [comment]
Resolved in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/113.
