### ISSUE TITLE
Bring in US Core extensions for patient profile

### ISSUE THREAD

**Issue by dwwinters** [ccsm-cds-tools/ccsm-cds-with-tests#32]
@dwwinters Why are there null values here when we know how these should be represented according to US Core?

_Originally posted by @mickohanlon23 in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/23#discussion_r918224821_

**Comment by mickohanlon23** [comment]
These have all been addressed in subsequent pull requests. [patientInfo](https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/blob/main/cql/DashboardLibrary.cql#L1206) no longer has `null` values for any of its fields.
