### ISSUE TITLE
Leverage dashboard codes

### ISSUE THREAD

**Issue by dwwinters** [ccsm-cds-tools/ccsm-cds-with-tests#33]
@dwwinters Many of these codes are now defined up to 4 times throughout the CDS. Could we make this DRYer by importing the codes from other libraries (i.e. from the Dashboard)? Or is the idea that we want them to be able to function somewhat independently from one another.

_Originally posted by @mickohanlon23 in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/23#discussion_r918228839_

**Comment by mickohanlon23** [comment]
Several refactors have taken place since this Issue was posted, some of which touched upon where codes are defined. Since this is just proposing a general refactor and not any new functionality, I will close this comment, as it is not pressing and will not actually add much value.
