### ISSUE TITLE
Should we update the return value text here to indicate that it is only returning a text representation of the date portion of the dateTime?

### ISSUE THREAD

**Issue by dwwinters** [ccsm-cds-tools/ccsm-cds-with-tests#34]
Should we update the return value text here to indicate that it is only returning a text representation of the date portion of the dateTime?

_Originally posted by @mickohanlon23 in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/23#discussion_r918209267_

**Comment by mickohanlon23** [comment]
Resolved in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/113.
