### ISSUE TITLE
Fix order set function

### ISSUE THREAD

**Issue by dwwinters** [ccsm-cds-tools/ccsm-cds-with-tests#44]
https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/blob/main/cql/OrderSetLibrary.cql#L27

This element should be "text" since this is supposed to be a CodeableConcept.

**Comment by mickohanlon23** [comment]
This was resolved in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/commit/762b5b75ef1c6fb2067e034d8c1698be1b0c5d72.
