### ISSUE TITLE
Merge Future Pregnancy Concerns section (I.3) into the normal recommendations for section I.

### ISSUE THREAD

**Issue by mickohanlon23** [ccsm-cds-tools/ccsm-cds-with-tests#53]
See email thread from Sharon titled: "Future pregnancy concerns"

**Comment by mickohanlon23** [comment]
Ginny and Sharon will review final text after it has been reviewed and updated by clinicians.

**Comment by ssebast2** [comment]
@mrnosal - can you confirm what Mick is asking above?

**Comment by mrnosal** [comment]
I.1 and I.2 recommendations should have language about future pregnancy concerns. I.3.x recommendation text does not include language about future pregnancy concerns, as those paths are not reachable unless there is an explicit data element (toggle switch or patient questionnaire resource) that indicates the affirmative. I.3.2 mentions FPC to explain when observation is acceptable.

**Comment by mickohanlon23** [comment]
I just confirmed what Mike mentioned above in the L3 code. A patient who is recommended treatment in response to a high grade histology in section I will now either:
1) fall into I.3 if they discretely have a `RecentlyRespondedYesToFuturePregnancyConcernsQuestion` status (i.e. from a toggle switch indicating future pregnancy concerns). These recommendations are tailored specifically to patients who have future pregnancy concerns
2) fall into I.1 or I.2. These recommendations do not require you discretely mentioning future pregnancy concerns, but the recommendations given within the sections contain text describing how to modify care with regards to pregnancy.

@ssebast2 @mrnosal I will close this issue out, as it has been resolved by the updated recommendation text, but feel free to re-open if you see any other potential concerns.
