### ISSUE TITLE
Update LP4 Logic for Avg Risk 21-29 year olds to pick up incorrect testing in the past.

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#55]
per Dr. Guido and Updike, we need to be prepared for messy date/inccorrect care and get the physicians back on track. For example, a patient under 30 may have been receiving cotesting or primary HPV testing. If so, we need to suggest cytology for the next screening.

**Comment by mickohanlon23** [comment]
Addressed in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/71. Keeping this open for now to look into changing recommendation text for a future screening for average risk patients under 30, to be more specific about what type of screening test the patient will be due for.

**Comment by mickohanlon23** [comment]
Recommendation text has been updated in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/76.
