### ISSUE TITLE
Update LP3 logic for 21-29 years olds to accomodate messy data

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#57]
Dr. Guido mentioned that data and provider practice can be imperfect. Although immunocompromised individuals that are 21-29 year old should be screened with cytology alone, there may be a chance that they are given a cotest. If that result is NILM/Neg, he feels it should be counted as one of the cytology tests. I have updated the logic to reflect this comment and am waiting for Ginny to review it. If she concurs, this logic should be updated in the L3. Thanks!

**Comment by ssebast2** [comment]
@mickohanlon23  - for individuals <=29 it must be a cytology alone or cytology component of a cotest (as long as the HPV portion is neg) to meet screening criteria. Of note - primary HPV testing is not appropriate for IC individuals of any age.

Regarding the way the L3 code was written - are you saying that the L3 NEVER looks for a 'cytology alone' test and/or result?

Ginny did review the updates I made to the L2 and concurs with them.

**Comment by mickohanlon23** [comment]
@ssebast2 
> Regarding the way the L3 code was written - are you saying that the L3 NEVER looks for a 'cytology alone' test and/or result?

No. The CDS code in logic path 3 only looks a cytology result, whether or not it was coupled with another HPV result in a cotest. This aligns with what you were saying - both negative cytology alone tests or cotests with negative HPV and cytology portions will count towards the annual cytology test count that Logic Path 3 looks for.

**Comment by mickohanlon23** [comment]
Closing this issue, since PR https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/72 adds tests to prove that the CDS currently operates as we would expect. No logic change was needed since our CDS already looked at cytology results that were a part of a cotest in logic path 3.
