### ISSUE TITLE
Update logic to care for patients >= 25 with cytology alone

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#58]
Dr. Guido feels that we should follow the errata (that has yet to be published) that says that LSIL or worse goes to colpo, then you move to the Common Abnormality tables. There are 4 open questions r/t this:
1. We don't have a copy of the most recent errata to build out the L2 and L3 appropriately. The last version we received is v6. We need to ask Jean to ask the Advisors for the most recent copy and find out if it is the FINAL version.
2. v6 says that >=25 and LSIL or worse goes to colpo. It doesn't mention how to care for an ASC-US result. We need to see if this is covered in the FINAL version or ask the Advisors about this scenario.
3. After the patient has a colpo, they move to Table 3. However, Table 3 does not cover all "cytology alone" scenarios (i.e., it provides care recommendations for ASC-H above (regardless of HPV result) and a biopsy result, but not a LSIL cytology result without an HPV result). We need to see if this is covered in the FINAL version or ask the Advisors about this scenario.
Note: Section K.1 handles individuals <25 with abnormal results.

**Comment by ssebast2** [comment]
Regarding above, I pulled the 2012 guidelines, which we can cite versus the unpublished errata, which may/may not cover all that we need. My preference is to use the FINAL version of the 2019 errata, which should be published any day now. Those statements are likely much more concise. Then we will only have to fall back to the 2012 guidelines for a small amount of care. 

It would be nice if the 2012 guidelines had a blanket statement that said "for cytology alone, if LSIL or worse, then get a colposcopy", but they don't. They do say: For women with LSIL cytology and no HPV test or a positive HPV test, colposcopy is recommended (AI). For women with ASC-H cytology, colposcopy is recommended regardless of HPV result. Reflex HPV testing is not recommended (DII). For women with HSIL cytology, **immediate loop electrosurgical excision or colposcopy is acceptable**, except in special populations (BII) (my note: it looks like women aged 21-24 are the only special population listed). Triage using either a program of repeat cytology alone or reflex HPV testing is unacceptable (EII). For women not managed with immediate excision, colposcopy is recommended regardless of HPV result obtained at co-testing (BII). Accordingly, reflex HPV testing is not recommended (BII). For women with all subcategories of AGC and AIS except
atypical endometrial cells, colposcopy with endocervical sampling is recommended regardless of HPV result (AII).

For #2, the 2012 guideline says: For women with ASC-US cytology and no HPV result, reflex HPV testing is preferred (BI). 
For women with ASC-US cytology and no HPV result, repeat cytology at 1 year is acceptable (BII). If the result is ASC-US or worse, colposcopy is recommended; if the result is negative, return to cytology testing at 3-year intervals is recommended (BII).

For #3, the 2012 guideline says: Management of Women With CIN 1 or No Lesion Preceded by ‘‘Lesser Abnormalities’’ (Fig. 13). Co-testing at 1 year is recommended (BII). If both the HPV test and cytology are negative, then age-appropriate retesting 3 years later is recommended (cytology if age is younger than 30 years, co-testing if 30 years of age or older). If all tests are negative, then return to routine screening is recommended (BII). If any test is abnormal, then colposcopy is recommended (CIII).

More to come once we see if we can get a copy of the FINAL 2019 errata.

**Comment by mickohanlon23** [comment]
Closing this issue as this will be addressed by Issue #63, which points to the section in the L2 with the updated logic.
