### ISSUE TITLE
Distinguish biopsy results taken during a colposcopy or ECC from biopsies taking during an excisional procedure (eg LEEP, laser cone biopsy)

### ISSUE THREAD

**Issue by gmmeadows** [ccsm-cds-tools/ccsm-cds-with-tests#60]
The ASCCP Guidelines clearly distinguish between biopsies taken during a colposcopy or ECC from those biopsies taken during an excisional procedure, and the appropriate next steps and/or care recommendation specifically for colposcopy or ECC biopsy results.

**Comment by ssebast2** [comment]
We've agreed that our formal CDS L2 and L3 will reason over the most severe of biopsy results that come from a 1) colpo procedure, or 2) a colpo and ECC procedure done on the same dateTime. 

We need to discuss if/how we accommodate biopsies that come from a) excisions, b) excisions w/ ECC on the same dateTime, and c) ECCs alone. See the table that was validated by Dr. Guido as far as what we would display in scenario a, b, and c.

**Comment by mickohanlon23** [comment]
See '[most severe](https://mitre.sharepoint.com/sites/CervicalCancerCDS/Shared%20Documents/CDS%20Development/L2%20Artifacts/Deliverables/CDC_CC_CDS_L2Development_v5_2.6.23.docx?d=wf7c476a6d04d48dcb865725e459dc24d&nav=eyJjIjo0MTQ1MjQ4Nn0&ne=ew0KICAidnQiOiB7DQogICAgImIiOiA5NTk3Nw0KICB9DQp9)' logic in L2

**Comment by mickohanlon23** [comment]
The Issue of determining the most severe of a collection of colpo/ECC biopsy results that occur on the same dateTime will be tracked in Issue https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/issues/59, which will be resolved more immediately. I will keep this issue open for discussion about the last part of @ssebast2's most recent comment:

> We need to discuss if/how we accommodate biopsies that come from a) excisions, b) excisions w/ ECC on the same dateTime, and c) ECCs alone. See the table that was validated by Dr. Guido as far as what we would display in scenario a, b, and c.

**Comment by mickohanlon23** [comment]
As a part of this, we should make sure that ECC procedures are included in the dashboard after being mapped.

**Comment by mickohanlon23** [comment]
ECC procedures have been mapped to dashboard. They are treated as cervical biopsies, just like colposcopy results. Issue https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/issues/59 is still open, but all other concerns brought up in this tickets are resolved.
