### ISSUE TITLE
Add logic for what to do when querying the Management Risk Tables without an HPV result.

### ISSUE THREAD

**Issue by mickohanlon23** [ccsm-cds-tools/ccsm-cds-with-tests#63]
@ssebast2

**Comment by ssebast2** [comment]
@mickohanlon23  - did you mean to leave me a message?

**Comment by mickohanlon23** [comment]
> @mickohanlon23 - did you mean to leave me a message?

@ssebast2 sorry for the unnecessary notification; I was opening Issues for all potential future code updates yesterday, and tagged you here for awareness since you are working on this issue from the clinical / L2 side. No questions for now. If you could just point me towards the updated logic for this issue once it is teased out, I can copy the resolution here so that a fix can be made in the L3.

**Comment by ssebast2** [comment]
@mickohanlon23  - See Section 4.7.3.3.12 in the L2 (4.7.3.3.12	 2023 Journal of Lower Genital Track Disease (JLGTD) Addendum to the 2019 ASCCP Guidelines) for what the 2023 errata document says to do in this scenario.

**Comment by mickohanlon23** [comment]
See PR https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/86
