### ISSUE TITLE
Review Logic for K.1.4 - Heading 4 - Patients Under 25 with CIN2

### ISSUE THREAD

**Issue by mickohanlon23** [ccsm-cds-tools/ccsm-cds-with-tests#69]
RE: Test Patient 37

Current logic indicates that CIN2 diagnoses need to happen within 2 years of each other, rather than CIN2 needing to persist for two years.

**Comment by ssebast2** [comment]
Dr. Guido said that if 'CIN2 or unspecified HSIL' is present 2 years after an initial 'CIN2 or unspecified HSIL', then treatment is indicated (this is in Section I.3.5), so our existing logic is incorrect. I sent an email to @mickohanlon23 and Ginny to 1) determine how to best express this logic change, and 2) whether it is worthwhile to align the approach with similar scenarios mentioned in the sections below.

- K.1.3 (< 25) - this mentions that the result persists at the 2 year f/u visit (where we time constrain the results to 2-2.5 years later)
- K.3.3 (Mgmt of CIN2 preceded by ASC-H/HSIL cytology)  - mentions labs that persist for 2 years (we constrain the time as > 18 month and < 3 years)
- I.4.5 - we contrain to >=2 years and < 3 years

**Comment by mickohanlon23** [comment]
Thanks @ssebast2. So if I am understanding correctly I should ignore the 3rd paragraph and bullet points. And the change is simply that the second histologic HSIL has to be >=2 years and <3 years apart from the first, rather than <= 2 years apart?

**Comment by ssebast2** [comment]
Correct!

**Comment by mickohanlon23** [comment]
This is resolved by pull request https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/82
