### ISSUE TITLE
Add USPSTF Grade D recommendation r/t not screening individuals < 21

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#73]
We included the Grade D recommendations in the L2 based on our Advisors feedback and now Dr. Guido's but they may have never been added to the L3. There are two logic clauses r/t screening ind. < 21 on page 29 of the L2 (i.e., LP 4A)

2.	GRADE D RECOMMENDATION: Screening is not indicated for individuals < 21 years of age 
IF Age < 21 years old
AND Cervical cytology result NOT FOUND
AND hrHPV result NOT FOUND
AND NOT ‘symptomatic’ < 3 months ago
DISPLAY: Per the USPSTF Grade D Recommendation, cervical cancer screening is not recommended for average-risk, asymptomatic individuals < 21 years of age

3.	If an individual < 21 years of age is screened and the results are “negative/NILM”, remind the clinician that screening is not indicated until the individual turns 21 years of age.
IF Age < 21 years old
AND NOT ‘symptomatic’ < 3 months ago
AND 
MOST RECENT ‘negative cervical cytology’ or ‘negative surveillance test’
AND NOT 
Cervical cytology result = “ASC-US” or “LSIL” or “ASC-H” or “AGC” or “HSIL+”
OR hrHPV result = “Positive”
BEFORE the MOST RECENT ‘negative cervical cytology’ or ‘negative surveillance test’
DISPLAY: Per the USPSTF Grade D Recommendation, cervical cancer screening is not recommended for average-risk, asymptomatic individuals < 21 years of age.
ELSE insert skip logic to move to Logic Path 4B

**Comment by mickohanlon23** [comment]
This issue is covered by Issue: https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/issues/37, which had been opened last year. I will close this one, since it is duplicative and the extra detail provided here is documented in the L2. Thanks for bringing this back to our attention @ssebast2!
