### ISSUE TITLE
Ensure childbearing ages are considered in the L3

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#74]
During UPMC testing, a woman outside of childbearing age >= 50 was provided a care recommendation that considered future pregnancy concerns. 

- Section I.3 of the L2 ensures that only women >=25 and <=50 are given future pregnancy care recommendations.
- In the Risk Table section of the logic (page 75-76) if management recommendation = "Treatment" or "Colposcopy/Treatment" there is special wording for individuals >=25 and <=50.

Could this be implemented in the L3 and not the app/care recommendations presented to clinicians @mickohanlon23 @mrnosal ?

**Comment by mickohanlon23** [comment]
Yes, this makes sense! We have added this to the high priority list. @mrnosal can you look into making this fix and coordinating with @ssebast2 as needed?

**Comment by mrnosal** [comment]
I only see mention of future pregnancy concerns for patients > 50 in ManageRareAbnormality.cql [I.1](https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/blob/4fab85e3e181386382590e8855500cbfedfcdc7f/cql/ManageRareAbnormality.cql#L829), [I.2.2](https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/blob/4fab85e3e181386382590e8855500cbfedfcdc7f/cql/ManageRareAbnormality.cql#L862) and [I.6](https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/blob/4fab85e3e181386382590e8855500cbfedfcdc7f/cql/ManageRareAbnormality.cql#L1191).

I do not see any other instances of patients > 50 receiving recommendation text regarding future pregnancy concerns. Sections I.3.x are all restricted to patients >=25 and <=50.

I do not see anywhere patients >50 receiving management recommendation for "Treatment" or "Colposcopy/Treatment" in ManageCommonAbnormality.cql are provided a care recommendation considering future pregnancy concerns. TreatmentWithPregnancyConcernsRecommendationText is only presented for patients 25-50.

Do you want to remove the text regarding future pregnancy concerns for I.1, I.2.2 and I.6 for patients > 50?

**Comment by mickohanlon23** [comment]
That makes sense to me. It could also be helpful to recreate the test scenario that originally brought this issue up within our CQL Testing Framework. I believe this was patient 19 in the Testing Spreadsheet, but @ssebast2 can confirm.

**Comment by ssebast2** [comment]
I believe it was patient #19 because there is a UPMC comment that mentions dropping the future pregnancy message b/c the patient is well over 50. Note: They did not include BPA or results for patient #19 in either round of testing, so it is hard to tell for sure. Dr. Guido agreed that 50 is a reasonable age to stop providing future pregnancy nuances. For that reason, I think individuals >50 do not need to receive future pregnancy nuances in sections I.1, I.2.2 and I.6.

**Comment by mrnosal** [comment]
Removed future pregnancy concern text from recommendations when patient is over 50. Added 3 tests. Please review updated text with @ssebast2

**Comment by ssebast2** [comment]
@mrnosal - can you please share the updated text?

**Comment by mrnosal** [comment]
@ssebast2 It's [linked in the commit](https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/commit/1fb534fd77d24ee45c94eb59dfb98d2eca817389) from yesterday. 

I.1 Age 25 to 50 (unchanged)
Treatment is preferred for histologic HSIL. Observation is acceptable if there are concerns related to future pregnancies and the following criteria are met: entire SCJ is visualized, lesion does not extend into endocervical canal, ECC is < CIN 2.
Observation, if elected includes colposcopy and HPV-based testing with cotest or primary hrHPV testing at 6-month intervals for up to 2 years.

I.1 Age > 50 (new)
Treatment is recommended for histologic HSIL.

I2.2 Age 25 to 50 (unchanged)
Treatment of CIN2 is recommended unless the patient\'s concerns about the effect of treatment on future pregnancy outweigh concerns about cancer.
Excisional treatment is preferred, and treatment with ablation is acceptable.
Observation is unacceptable when the squamocolumnar junction or the upper limit of the lesion is not fully visualized or when the results of an endocervical sampling, if performed, is CIN 2+ or ungraded.
Observation includes colposcopy and HPV-based testing with cotest or primary hrHPV testing at 6-month intervals for up to 2 years.

I2.2 Age > 50 (new)
Treatment of CIN2 is recommended.
Excisional treatment is preferred, and treatment with ablation is acceptable.

I.6 Age 25 to 50 (unchanged)
A diagnostic excisional procedure is recommended for all patients with a diagnosis of AIS on cervical biopsy to rule out invasive adenocarcinoma.
After the initial diagnostic procedure, hysterectomy is the preferred management for all patients who have a histologic diagnosis of AIS, although fertility-sparing management for appropriately selected patients is acceptable.
For patients who undergo fertility-sparing management, surveillance with cotesting and endocervical sampling is recommended every 6 months for at least 3 years, then annually for at least 2 years, or until hysterectomy is performed.

I.6 Age > 50 (new)
A diagnostic excisional procedure is recommended for all patients with a diagnosis of AIS on cervical biopsy to rule out invasive adenocarcinoma.
After the initial diagnostic procedure, hysterectomy is the preferred management for all patients who have a histologic diagnosis of AIS.

**Comment by ssebast2** [comment]
@mrnosal - the changes you made look good :)

**Comment by mickohanlon23** [comment]
This is resolved by PR https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/80
