### ISSUE TITLE
Update Recommendation Text in Section I.3.1

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#77]
The 2023 Errata paper made a very slight change to the recommendation text in the above section (i.e., change "squamocolumnar junction is visible " to "squamocolumnar junction is fully visualized". See below

DISPLAY For patients with a diagnosis of histologic HSIL (CIN 2) whose concerns about the effects of treatment on a future pregnancy outweigh their concerns about cancer, either observation or treatment is acceptable provided the squamocolumnar junction is fully visualized and CIN 2+ or ungraded CIN is not identified on endocervical sampling (CII). For patients 25 years or older, observation includes colposcopy and HPV-based testing with cotest or primary hrHPV testing at 6-month intervals for up to 2 years.

**Comment by mickohanlon23** [comment]
This is addressed in PR: https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/81. Can be closed here.
