### ISSUE TITLE
Update r/t clinical lessons learned from the pilot: Manage absence of pathology history prior to having an excision with a biopsy (edited)

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#83]
The logic below (reviewed by Ginny) provides a care recommendation for a patient that has no prior pathology results prior to an excision with a biopsy:

IF cytology result OR histology result NOT FOUND BEFORE 'treatment'
AND histology test FOUND on same dateTime as 'treatment'
WHERE the result = "<CIN1" or "Histologic LSIL (CIN1)" or   "Histologic HSIL (CIN2)" or "Histologic HSIL,   unspecified" or "Histologic HSIL (CIN3)"
THEN DISPLAY HPV-based testing is recommended in 6 months
AND manage these follow up results as outlined in Table 5A, followed by Table 5B

**Comment by ssebast2** [comment]
See the spreadsheet for the updated (i.e., corrected) and more specific logic!

**Comment by mickohanlon23** [comment]
Updated logic described in comments of [CCSMCDS-7](https://jira.mitre.org/browse/CCSMCDS-7).

**Comment by mickohanlon23** [comment]
Resolved in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/111
