### ISSUE TITLE
Fix error in the 'negative cervical cytology series' variable logic

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#85]
Originally, it was written to only accept 'negative cytology alone' events. It was recently updated to try to accept a negative cytology that was alone or a part of a cotest. However, I forgot to specify that the HPV had to be Negative if the cytology was NILM - so it is wrong. 

I'm trying to determine the best way to allow either a 'negative cytology' OR a 'negative cotest' as part of the series. It is easy to write the logic if you are looking for a series of 3 'negative cytology' events OR 3 'negative cotest' in a row, but trickier to accept a variety of tests that occur within the designated time frame (e.g., 'negative cytology' then 'negative cotest' then 'negative cytology').

Would this work:

**Define ‘negative cervical cytology or cotest’ as:** 
‘negative cervical cytology’ or ‘negative cotest’ 

**Define ‘negative cervical cytology series’ as:**
‘negative cervical cytology or cotest’
AND SECOND ‘negative cervical cytology or cotest’ AND dateTime of this test is >=12 months AND <= 18 months BEFORE the dateTime of the FIRST ‘negative cervical cytology or cotest’
AND THIRD ‘negative cervical cytology or cotest’ AND dateTime of this test is >=12 months AND <= 18 months BEFORE the dateTime of the SECOND ‘negative cervical cytology or cotest’

**Comment by mickohanlon23** [comment]
I don't think this is actually an issue in our L3. Our CQL logic here only looks for cytology tests, and ignores HPV tests. So cytologies that came from a 'cytology alone' test or that came from 'cotest' would both be included.

If any HPV or Cytology test in their recent history is abnormal, they would be excluded from this logic path, so specifically indicating that HPV has to be negative isn't necessary.

**Comment by ssebast2** [comment]
This 'error' has been fixed in the L2. It was never a problem in the L3, therefore I am closing this issue.
