### ISSUE TITLE
Placeholder: Additional Recommendation Text Updates

### ISSUE THREAD

**Issue by mrnosal** [ccsm-cds-tools/ccsm-cds-with-tests#91]
Placeholder issue for late-breaking recommendation text updates before go-live.

**Comment by mickohanlon23** [comment]
Hysterectomy text has been updated so that screening hysterectomy recommendation now includes the agreed upon text that includes surveillance instructions if hysterectomy was done to manage a CIN2 or CIN3 pre-cancer result.

**Comment by mickohanlon23** [comment]
This Issue will now be to add a non-recommendation for when a patient <25 years old has a NILM cytology with HPV+ cotest. This recommendation should be prioritized after all of our current recommendations, and should say something along the lines of:

> Guidelines do not provide guidance for a patient <25 with a NILM and HPV+ cotest. Please use clinical judgement.

**Comment by mickohanlon23** [comment]
- <25 years NILM cytology with HPV+ cotest recommendation text has been added in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/101
- Other general recommendation text edits, including those around hysterectomy (mentioned above) have been added in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/112.

I will close this issue, as no other recommendation text updates are critical for go-live.
