### ISSUE TITLE
Update r/t clinical lessons learned from the pilot: Manage AIS found outside of a colpo or colpo with ECC

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#92]
To ensure appropriate follow up if AIS found outside of a colpo or colpo with ECC:

IF histology test FOUND on same dateTime as a 'treatment' or an ECC procedure
AND the result = "Histologic AIS"
THEN DISPLAY Refer to   Gynecologic Oncology

**Comment by mickohanlon23** [comment]
@ssebast2 Aren't there other proposed "Refer to Gynecologic Oncology" scenarios? Can we document them all here?

**Comment by mickohanlon23** [comment]
Or is it just this one other issue: https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/issues/93?

**Comment by ssebast2** [comment]
The problem is that they require different logic. See https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/issues/93

**Comment by ssebast2** [comment]
Yes, it is just that one other issue

**Comment by mickohanlon23** [comment]
Logic for managing AIS has been added in PR: https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/109. Mapping of AIS Excisional Biopsy results was added in PR: https://github.com/ccsm-cds-tools/ccsm-cds-service/pull/20. Together, these two PRs will allow for an AIS result from an excision to be mapped from the SmartForm and managed appropriately in our CDS.
