### ISSUE TITLE
Update r/t clinical lessons learned from the pilot: Provide care recommendation for Histologic cancer result

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#93]
Regardless of what procedure generated the biopsy and result, if histologic cancer is found, the patient should be referred to GYN ONC.

IF histology test FOUND
AND the result = "Histologic cancer"
THEN DISPLAY Refer to Gynecologic Oncology

**Comment by mickohanlon23** [comment]
Logic for this is addressed by PR: https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/108. Mapping of histologic cancer excision results is done in https://github.com/ccsm-cds-tools/ccsm-cds-service/pull/20.
