### ISSUE TITLE
Update r/t clinical lessons learned from the pilot: Provide care recommendation for an ECC <= CIN3 that occurs outside of an excision or colpo 

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#94]
If an ECC procedure is performed alone (i.e., not during a colpo or excision) and the result is <=CIN3, there is not enough evidence to tell the clinician what to do. Dr. Updike said to use clinical judgement.

IF histology test FOUND on the same dateTime as an ECC procedure
AND the result = "<CIN1" or "Histologic LSIL (CIN1)" or "Histologic HSIL (CIN2)" or "Histologic HSIL, unspecified" or "Histologic HSIL (CIN3)" AND NOT coloposcopy procedure or 'treatment' on the same dateTime as the ECC procedure
THEN DISPLAY "Use clinical judgement to manage care based on a biopsy result obtained during an ECC procedure."

**Comment by ssebast2** [comment]
NO!! This is old and is no longer relevant! 

This is no longer relevant. 

This is the updated logic. Note: We still need to clarify with the doctors what the care recommendation is in this scenario.
IF histology test FOUND on the same dateTime as an ECC procedure
AND the result = "<CIN1" or "Histologic LSIL (CIN1)"
AND NOT colposcopy procedure or 'treatment' on the same dateTime as the ECC procedure
THEN DISPLAY xxx

**Comment by mickohanlon23** [comment]
This has been updated even further since. We have decided that ECCs are mapped to cervical biopsies the same way as colposcopies are. Therefore, this issue is already resolved.
