### ISSUE TITLE
Update r/t clinical lessons learned from the pilot: Find appropriate mapping for ECC "HSIL"

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#95]
Since we now have to be able to reason over all ECC results, there is one result that has not yet been mapped (HSIL). Dr. Guido and/or Updike will need to review every piece of logic in our L2 that uses "Histologic HSIL, unspecified" to determine if that would be an appropriate mapping for ECC "HSIL".

**Comment by ssebast2** [comment]
okay, we'll see what they say

**Comment by mickohanlon23** [comment]
According to Issue https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/issues/97, ECC "HSIL" should now be mapped to  **Histologic HSIL, (CIN3)**.

**Comment by ssebast2** [comment]
ECC HSIL should be mapped to Histologic HSIL, CIN3!!
