### ISSUE TITLE
CDS Go Live Update: Ensure appropriate follow up if HSIL (i.e., Histologic HSIL, (CIN3)) is found during an ECC alone

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#97]
Ensure appropriate follow up if HSIL (i.e., Histologic HSIL, (CIN3)) is found during an ECC alone. An ECC result of 'HSIL' is covered if it occurs during a colpo or during a treatment, but we don't currently cover it if it occurs outside of those procedures.

IF histology test FOUND on the same dateTime as an ECC procedure
AND the result = "Histologic HSIL (CIN3)"
AND NOT colposcopy procedure or 'treatment' on the same dateTime as the ECC procedure
THEN DISPLAY Treatment is recommended

**Comment by mickohanlon23** [comment]
ECCs are mapped to cervical biopsies in the same way as colposcopies are, therefore this issues has been addressed. See references above for more details about code updates that touched upon this issue.
